### ISSUE TITLE
Inconsistent cursor on clickable items

### ISSUE THREAD

**Issue by catos** [DjPale/grabtangle-cloud#11]

**Comment by DjPale** [comment]
@catos I guess you are referring to the toggle buttons which shows cursor and not "hand"?

![bilde](https://user-images.githubusercontent.com/1427902/59586326-f477a080-90e2-11e9-96a5-282f8513863f.png)

**Comment by DjPale** [comment]
This is an issue with the underlying framework, some discussion going on here: https://github.com/twbs/bootstrap - but I agree that it should be a hand pointer.
