### ISSUE TITLE
Add task, selected "date" is not shown

### ISSUE THREAD

**Issue by catos** [DjPale/grabtangle-cloud#7]

**Comment by DjPale** [comment]
@catos it is shown, but there are no clear visual queues when changed.

![bilde](https://user-images.githubusercontent.com/1427902/59586181-934fcd00-90e2-11e9-9c9b-7847167d251c.png)

**Comment by DjPale** [comment]
Better visualized in 29570b4a35f57756b16f35b520e318886b95d2f8
