### ISSUE TITLE
When refreshing the browser, the login options are shown briefly even if you are already logged in

### ISSUE THREAD

**Issue by catos** [DjPale/grabtangle-cloud#9]

**Comment by DjPale** [comment]
Related to #5

**Comment by DjPale** [comment]
Possibly stand-alone issue. There is a way to add some visual indicators as shown in this example: https://fir-ui-demo-84a6c.firebaseapp.com/

**Comment by DjPale** [comment]
Tried a lot - but could not fix this, https://www.npmjs.com/package/react-firebaseui#accessing-the-firebaseui-instance does not seem to work for some reason either. Leaving this code in case it works when token expires or similar.
